sudo: required
dist: focal

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - souce $HOME/google-cloud-sdk/path.bash.inc
  - gloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

  - gcloud config set project multi-k8s-413113
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster

  - eche "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t burnsmarty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true burnsmarty/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
